---
default_install_hook_types:
  - pre-commit
  - pre-merge-commit
  - pre-push
  - prepare-commit-msg
  - commit-msg
  - post-commit
  - post-checkout
  - post-merge
  - post-rewrite
fail_fast: false

repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.25
    hooks:
      - id: actionlint
        stages: [commit]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint-docker
        stages: [commit]
  - repo: meta
    hooks:
      - id: check-hooks-apply
        stages: [manual]
      - id: check-useless-excludes
        stages: [manual]
      - id: identity
        stages: [manual]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: check-ast
        stages: [commit]
      - id: check-executables-have-shebangs
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-shebang-scripts-are-executable
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
