---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: celery-crd-custodian
rules:
  - apiGroups:
      - celeryq.dev
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - create
      - delete
