---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: celery-crd-custodian
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: celery-crd-custodian
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ""
