---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: celery-job-dispatcher
  namespace: ""
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: celery-job-dispatcher
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ""
